### ISSUE TITLE
can't parse the StackOverflow Careers feed

### ISSUE THREAD

**Issue by emilburzo** [rometools/rome#192]
Link to the feed: http://careers.stackoverflow.com/jobs/feed?allowsremote=True

~~pubDate returned: <pubDate>Mon, 13 Oct 2014 19:22:40 Z</pubDate>~~

Previous issue fixed by adding

```
datetime.extra.masks=yyyy-MM-dd'T'HH:mm:ss|EEE, dd MMM HH:mm:ss Z
```

to rome.properties.

But now I'm getting:
```
java.lang.IllegalArgumentException: Invalid document
	at com.rometools.rome.io.WireFeedInput.build(WireFeedInput.java:291)
	at com.rometools.rome.io.WireFeedInput.build(WireFeedInput.java:213)
	at com.rometools.rome.io.SyndFeedInput.build(SyndFeedInput.java:133)
```

**Comment by mishako** [comment]
@emilburzo Rome 1.6.0 has been released with this issue fixed.
