### ISSUE TITLE
[fetcher] If remote server redirects to different location ROME throws ParsingFeedException

### ISSUE THREAD

**Issue by mishako** [rometools/rome#222]
<a href="https://github.com/to-kra"><img src="https://avatars.githubusercontent.com/u/2188084?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [to-kra](https://github.com/to-kra)**
_Monday Jan 18, 2016 at 15:57 GMT_
_Originally opened as https://github.com/rometools/rome-fetcher/issues/21_

----

feed: `http://jazz.net/library/rss/?project=rational-team-concert&amp;tag=source control',this`

makes one redirect

and there is this exception thrown:
`[err] com.sun.syndication.io.ParsingFeedException: Invalid XML: Error on line 7: The element type "HR" must be terminated by the matching end-tag "</HR>".
[err] 	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:198)
[err] 	at com.sun.syndication.io.SyndFeedInput.build(SyndFeedInput.java:123)
[err] 	at com.sun.syndication.fetcher.impl.HttpURLFeedFetcher.readSyndFeedFromStream(HttpURLFeedFetcher.java:272)
[err] 	at com.sun.syndication.fetcher.impl.HttpURLFeedFetcher.getSyndFeedFromStream(HttpURLFeedFetcher.java:277)
[err] 	at com.sun.syndication.fetcher.impl.HttpURLFeedFetcher.resetFeedInfo(HttpURLFeedFetcher.java:191)
[err] 	at com.sun.syndication.fetcher.impl.HttpURLFeedFetcher.retrieveAndCacheFeed(HttpURLFeedFetcher.java:163)
[err] 	at com.sun.syndication.fetcher.impl.HttpURLFeedFetcher.retrieveFeed(HttpURLFeedFetcher.java:119)
[err] 	at com.ibm.kc.jaxrs.v1.FeedService.getFeeds(FeedService.java:36)
[err] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[err] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[err] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[err] 	at java.lang.reflect.Method.invoke(Method.java:606)
[err] 	at org.apache.wink.server.internal.handlers.InvokeMethodHandler.handleRequest(InvokeMethodHandler.java:63)
[err] 	at org.apache.wink.server.handlers.AbstractHandler.handleRequest(AbstractHandler.java:33)
[err] 	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)
[err] 	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)
[err] 	at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:75)
[err] 	at org.apache.wink.server.internal.handlers.CreateInvocationParametersHandler.handleRequest(CreateInvocationParametersHandler.java:54)
[err] 	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)
[err] 	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)
[err] 	at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:75)
[err] 	at org.apache.wink.server.internal.handlers.FindResourceMethodHandler.handleResourceMethod(FindResourceMethodHandler.java:151)
[err] 	at org.apache.wink.server.internal.handlers.FindResourceMethodHandler.handleRequest(FindResourceMethodHandler.java:65)
[err] 	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)
[err] 	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)
[err] 	at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:75)
[err] 	at org.apache.wink.server.internal.handlers.FindRootResourceHandler.handleRequest(FindRootResourceHandler.java:95)
[err] 	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)
[err] 	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)
[err] 	at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:75)
[err] 	at org.apache.wink.server.internal.handlers.HeadMethodHandler.handleRequest(HeadMethodHandler.java:53)
[err] 	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)
[err] 	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)
[err] 	at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:75)
[err] 	at org.apache.wink.server.internal.handlers.OptionsMethodWADLHandler.handleRequest(OptionsMethodWADLHandler.java:51)
[err] 	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)
[err] 	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)
[err] 	at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:75)
[err] 	at org.apache.wink.server.internal.handlers.SearchResultHandler.handleRequest(SearchResultHandler.java:33)
[err] 	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)
[err] 	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)
[err] 	at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:75)
[err] 	at org.apache.wink.server.internal.log.ResourceInvocation.handleRequest(ResourceInvocation.java:92)
[err] 	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)
[err] 	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)
[err] 	at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:75)
[err] 	at org.apache.wink.server.internal.log.Requests.handleRequest(Requests.java:76)
[err] 	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)
[err] 	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)
[err] 	at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:75)
[err] 	at org.apache.wink.server.handlers.AbstractHandlersChain.run(AbstractHandlersChain.java:60)
[err] 	at org.apache.wink.server.internal.RequestProcessor.handleRequestWithoutFaultBarrier(RequestProcessor.java:207)
[err] 	at org.apache.wink.server.internal.RequestProcessor.handleRequest(RequestProcessor.java:154)
[err] 	at com.ibm.websphere.jaxrs.server.IBMRestServlet.service(IBMRestServlet.java:106)
[err] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
[err] 	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1275)
[err] 	at [internal classes]
[err] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
[err] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
[err] 	at java.lang.Thread.run(Thread.java:745)`

**Comment by mishako** [comment]
<a href="https://github.com/to-kra"><img src="https://avatars.githubusercontent.com/u/2188084?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [to-kra](https://github.com/to-kra)**
_Monday Jan 18, 2016 at 15:58 GMT_

----

do you handle redirects in your http client ?

**Comment by mishako** [comment]
<a href="https://github.com/mishako"><img src="https://avatars.githubusercontent.com/u/202554?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mishako](https://github.com/mishako)**
_Tuesday Jan 19, 2016 at 22:55 GMT_

----

Rome's `HttpURLFeedFetcher` doesn't support cross-protocol redirects (i.e. http-https), because Java's `URL` doesn't. I don't know if `HttpClientFeedFetcher` is better, but you could try it.

**Comment by mishako** [comment]
<a href="https://github.com/to-kra"><img src="https://avatars.githubusercontent.com/u/2188084?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [to-kra](https://github.com/to-kra)**
_Wednesday Jan 20, 2016 at 07:44 GMT_

----

@mishako But does it handle redirects at all ?  I could do check by myself with some apache http client to check status code - if 3xx then redirect, get redirect location, then do fetch of Feed from redirected location. `https` does not matter for now, I wanted to point out general redirect - can you state that fetcher does handle redirects ? and do you have any example how to use `HttpClientFeedFetcher` ?
Thank you in advance !

**Comment by mishako** [comment]
<a href="https://github.com/to-kra"><img src="https://avatars.githubusercontent.com/u/2188084?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [to-kra](https://github.com/to-kra)**
_Wednesday Jan 20, 2016 at 11:51 GMT_

----

By using:
`FeedFetcher feedFetcher = new HttpClientFeedFetcher(feedInfoCache);`

redirects works fine.
