### ISSUE TITLE
Loading Reddit

### ISSUE THREAD

**Issue by Steveaxelrod007** [rometools/rome#341]
When I try to load "http://www.reddit.com/.rss" I get

com.rometools.rome.io.ParsingFeedException: Invalid XML: Error on line 1: Premature end of file.
	at com.rometools.rome.io.WireFeedInput.build(WireFeedInput.java:236)
	at com.rometools.rome.io.SyndFeedInput.build(SyndFeedInput.java:150)
	at com.axee.safetyNet.SearchTopNews.getFeed(SearchTopNews.java:557)
	at com.axee.safetyNet.SearchTopNews.lambda$goodUrls$5(SearchTopNews.java:90)
	at com.axee.safetyNet.SearchTopNews$$Lambda$14/2041039871.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

I checked the XML and it looks fine and the XML validator says it is ok.

Thank you.

**Comment by mishako** [comment]
Closing in favor of #340

**Comment by Steveaxelrod007** [comment]
Is 340 and 341 same issue?

**Comment by mishako** [comment]
I think it is. But if we find out that it isn't, I will reopen it.
