### ISSUE TITLE
[modules] Handling bad values

### ISSUE THREAD

**Issue by djvergel** [rometools/rome#342]
When I try to load [Compromised RSS.txt](https://github.com/rometools/rome/files/1139397/Compromised.RSS.txt) I get:

Exception in thread "main" java.lang.NumberFormatException: multiple points
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1914)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at com.rometools.modules.georss.SimpleParser.parsePosList(SimpleParser.java:55)
	at com.rometools.modules.georss.SimpleParser.parseSimple(SimpleParser.java:110)
	at com.rometools.modules.georss.SimpleParser.parse(SimpleParser.java:68)
	at com.rometools.rome.io.impl.ModuleParsers.parseModules(ModuleParsers.java:52)
	at com.rometools.rome.io.impl.BaseWireFeedParser.parseItemModules(BaseWireFeedParser.java:87)
	at com.rometools.rome.io.impl.RSS090Parser.parseItem(RSS090Parser.java:308)
	at com.rometools.rome.io.impl.RSS091UserlandParser.parseItem(RSS091UserlandParser.java:269)
	at com.rometools.rome.io.impl.RSS092Parser.parseItem(RSS092Parser.java:104)
	at com.rometools.rome.io.impl.RSS093Parser.parseItem(RSS093Parser.java:43)
	at com.rometools.rome.io.impl.RSS094Parser.parseItem(RSS094Parser.java:68)
	at com.rometools.rome.io.impl.RSS090Parser.parseItems(RSS090Parser.java:278)
	at com.rometools.rome.io.impl.RSS090Parser.parseChannel(RSS090Parser.java:184)
	at com.rometools.rome.io.impl.RSS091UserlandParser.parseChannel(RSS091UserlandParser.java:82)
	at com.rometools.rome.io.impl.RSS092Parser.parseChannel(RSS092Parser.java:58)
	at com.rometools.rome.io.impl.RSS094Parser.parseChannel(RSS094Parser.java:47)
	at com.rometools.rome.io.impl.RSS090Parser.parse(RSS090Parser.java:82)
	at com.rometools.rome.io.WireFeedInput.build(WireFeedInput.java:314)
	at com.rometools.rome.io.WireFeedInput.build(WireFeedInput.java:234)
	at com.rometools.rome.io.SyndFeedInput.build(SyndFeedInput.java:150)

The code is pretty simple:

		SyndFeedInput input = new SyndFeedInput();

		File file = new File("Compromised RSS.txt");
		BufferedReader reader = new BufferedReader(new XmlReader(file));
		SyndFeed feed = input.build(reader);

There is some bad data in the RSS (second entry) and I don't expect it to successfully parse that entry. It would be nice though if it just handled that entry and maybe logged an error and continued parsing the rest of the document.

**Comment by mishako** [comment]
Thanks for submitting the issue! I completely agree with you, Rome shouldn't blow up because of a broken data in one of the tags.

I'm not sure how hard it would be to fix it. I guess fixing one module (GeoRSS) should not be very time-consuming. Would you be able to do it and submit the fix as a pull-request?

**Comment by djvergel** [comment]
I might not be able to look at it right away but if it's not urgent, I could eventually get to it.

What is the expectation in this case? If a bad value is encountered, should `ModuleParser.parse()` just return a null value?

**Comment by mishako** [comment]
I'm not sure if we do it consistently across all codebase. But I think yes, if some value is not valid, it should return null for that value.
