### ISSUE TITLE
NPE when parsing The Verge RSS 

### ISSUE THREAD

**Issue by strangerweather** [rometools/rome#670]
Hi, thanks for this valuable tool.

I am able to parse pretty much all the feeds I've tried but I have a problem with: https://www.theverge.com/google/rss/index.xml
Any ideas?

This is the parsing code that I use: 

```
class FeedParser {
    fun parse(xml: String, feedTitle: String, url: String): List<NewsFeed> {
        val formatter = DateTimeFormatter.ofPattern("MMMM dd, yyyy | k:mm")
        val input = SyndFeedInput()
        val feed = input.build(xml.reader())
        var title: String
        var pubDate: String
        var description: String
        var link: String
        val articlesFeed = mutableListOf<NewsFeed>()
        val id = 0L
        val dateTime = LocalDateTime.now().format(formatter)

        for (entry in feed.entries) {
                title = entry.title.parseAsHtml().toString()
                description = entry.description.value.parseAsHtml().toString()
                pubDate = entry.publishedDate.toString().parseAsHtml().toString()
                link = entry.link.parseAsHtml().toString()


        val feedItem = FeedItem(title, pubDate, description, link)

        val articleFeed = NewsFeed(
            feedItem = feedItem,
            feedTitle = feedTitle,
            url = url,
            id = id,
            updated = dateTime
        )
        articlesFeed.add(articleFeed)
    }
        return articlesFeed
    }
}
```

And this is the error that I get:

```
> java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String com.rometools.rome.feed.synd.SyndContent.getValue()' on a null object reference
2023-06-04 14:48:20.760  4145-4206  System.err              com.strangerweather.news             W  	at com.strangerweather.news.presentation.data.FeedParser.parse(FeedParser.kt:28)
2023-06-04 14:48:20.760  4145-4206  System.err              com.strangerweather.news             W  	at com.strangerweather.news.presentation.repositories.NetworkRepositoryImpl.parseFeedItemsAndSaveNewsFeed(NetworkRepositoryImpl.kt:49)
2023-06-04 14:48:20.760  4145-4206  System.err              com.strangerweather.news             W  	at com.strangerweather.news.presentation.repositories.NetworkRepositoryImpl$parseFeedItemsAndSaveNewsFeed$1.invokeSuspend(Unknown Source:15)
2023-06-04 14:48:20.760  4145-4206  System.err              com.strangerweather.news             W  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2023-06-04 14:48:20.760  4145-4206  System.err              com.strangerweather.news             W  	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2023-06-04 14:48:20.760  4145-4206  System.err              com.strangerweather.news             W  	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
2023-06-04 14:48:20.760  4145-4206  System.err              com.strangerweather.news             W  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
2023-06-04 14:48:20.760  4145-4206  System.err              com.strangerweather.news             W  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
2023-06-04 14:48:20.760  4145-4206  System.err              com.strangerweather.news             W  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by antoniosanct** [comment]
Hi, @strangerweather 

<description> is null at this location. You can find Atom 1.0 <content> node in getContents(), at SyndEntry class

Regards!
Antonio.

**Comment by antoniosanct** [comment]
Hi, @strangerweather 

I think it is a particularity on those Atom 1.0 resources. Theirs entries don't fill the summary node, field that ROME expects to be a little description of the entire entry.

The other question... ROME documentation doesn't have a comparison table between Atom entry and SyndEntry ROME object that helps you to answer. I'm sorry I can't help with this. Feel free to improve ROME docs that helps to understand it.

Regards,
Antonio.

**Comment by strangerweather** [comment]
Many thanks for your help! :-)
